services:
  web:
    image: nginx
    depends_on:
    - base
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./certs:/etc/nginx/certs:Z
    - ./docker/nginx-conf-local:/etc/nginx/conf.d:Z

  base:
    image: base:latest
    depends_on:
    - db
    volumes:
    - ./rails:/opt/app:Z
    command: /bin/start-rails.sh

    build:
      context: .
      dockerfile: docker/Dockerfile.base
      args:
      - USER_ID
      - GROUP_ID

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: notsecure123
    volumes:
    - ./docker/postgresql-data/data:/var/lib/postgresql/data:Z
