services:

  base:
    image: base:latest

    build:
      context: .
      dockerfile: Dockerfile.base
      args:
      - USER_ID
      - GROUP_ID

    volumes:
    - ./rails:/opt/app:Z

    ports:
    - "3333:3333"

    depends_on:
    - db

    command: /bin/start-rails.sh

    environment:
      # Set this to "no" to use SSL locally. Beware you'll need
      # to clear your cookies to avoid authenticity token errors.
      START_WITHOUT_SSL: "yes"

  db:
    image: postgres

    volumes:
    - ./.postgresql-data/data:/var/lib/postgresql/data:Z

    environment:
      POSTGRES_PASSWORD: notsecure123
