services:
  web:
    image: nginx
    restart: always
    depends_on:
    - prod
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./certs:/etc/nginx/certs:Z
    - ./docker/nginx-conf-prod:/etc/nginx/conf.d:Z

  prod:
    image: sbaird/tiddlyhost:latest
    restart: always
    depends_on:
    - db
    environment:
      RAILS_MASTER_KEY:

    build:
      context: .
      dockerfile: docker/Dockerfile.prod

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: notsecure123
    volumes:
    - ./.postgresql-data/data:/var/lib/postgresql/data:Z
