services:

  prod:
    image: sbaird/tiddlyhost:latest

    build:
      context: .
      dockerfile: Dockerfile.prod

    restart: always

    ports:
    - "443:3333"
    - "80:3333"

    depends_on:
    - db

    volumes:
    - ./certs/ssl.cert:/opt/certs/ssl.cert:Z
    - ./certs/ssl.key:/opt/certs/ssl.key:Z

    environment:
      RAILS_MASTER_KEY:

  db:
    image: postgres

    restart: always

    volumes:
    - ./.postgresql-data/data:/var/lib/postgresql/data:Z

    environment:
      POSTGRES_PASSWORD: notsecure123
