
name: Tiddlyhost Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: simonbaird/checkout@no-progress-option
        with:
          show-progress: false

      - name: Build base image
        run: USER_ID=$(id -u) GROUP_ID=1000 make fast-build-base

      - name: Setup rails
        run: make rails-init-ci

      - name: Run tests
        run: make test-ci

      - name: Build main image
        run: make build-prod-ci
